# Generated by Django 5.0.3 on 2024-06-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namear', models.CharField(max_length=255)),
                ('nameen', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('HoteStars', models.SmallIntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('descar', models.TextField()),
                ('descen', models.TextField()),
                ('policyen', models.TextField()),
                ('policyar', models.TextField()),
                ('icons', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='booking.groups')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel'),
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameen', models.CharField(max_length=255)),
                ('namear', models.CharField(max_length=255)),
                ('descar', models.TextField()),
                ('descen', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phototype', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='hotel/photos')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namear', models.CharField(max_length=255)),
                ('nameen', models.CharField(max_length=255)),
                ('descar', models.TextField()),
                ('descen', models.TextField()),
                ('guestgoup', models.TextField(blank=True, null=True)),
                ('Roomicons', models.TextField(blank=True, null=True)),
                ('roombeds', models.TextField(blank=True, null=True)),
                ('roomguests', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='room/images')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='StopSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
    ]
