# Generated by Django 5.0.3 on 2024-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_hotel_accounting_email_hotel_accounting_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='b2b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='b2c',
            field=models.SmallIntegerField(null=True),
        ),
    ]
