# Generated by Django 5.0.3 on 2024-07-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_hotel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReservationCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['namear']},
        ),
        migrations.CreateModel(
            name='RoomBedOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('number', models.PositiveSmallIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomGuestoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('number', models.PositiveSmallIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='Manualreservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('req', 'requested'), ('w', 'waiting'), ('cnc', 'collection not confirmed'), ('con', 'confirmed'), ('col', 'collected'), ('com', 'completed'), ('can', 'canceled')], max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
                ('bedoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roombedoptions')),
                ('guestoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomguestoption')),
            ],
        ),
    ]
