# Generated by Django 5.0.3 on 2024-07-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_hotel_b2b_alter_hotel_b2c'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booking.hotel'),
        ),
    ]
