# Generated by Django 5.0.3 on 2024-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_manualreservationcustomer_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(default=1, upload_to='hotel/logos'),
            preserve_default=False,
        ),
    ]
