# Generated by Django 5.0.3 on 2024-07-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hotel_user_name_alter_groups_hotel_alter_hotel_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='reservation_email_phone',
            new_name='reservation_phone',
        ),
    ]
