# Generated by Django 5.0.3 on 2024-07-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_reservation_email_phone_hotel_reservation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='extraservices',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='manualreservations',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manualreservations', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealplans', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='periods',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='stopsale',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopsale', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplement', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='update',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='users',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='booking.hotel'),
        ),
    ]
