# Generated by Django 5.0.3 on 2024-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_hotel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/logos'),
        ),
    ]
