# Generated by Django 5.0.3 on 2024-07-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_hotel_contract_attachement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractattachement',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractAttachment', to='booking.hotel'),
        ),
    ]
