# Generated by Django 5.0.3 on 2024-07-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_hotel_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Roomicons',
            new_name='roomicons',
        ),
        migrations.RemoveField(
            model_name='room',
            name='guestgoup',
        ),
        migrations.AddField(
            model_name='room',
            name='logo',
            field=models.ImageField(default=1, upload_to='rooms/logos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roombedoptions',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedoptions', to='booking.room'),
        ),
        migrations.AlterField(
            model_name='roomguestoption',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestoptions', to='booking.room'),
        ),
    ]
