# Generated by Django 5.0.3 on 2024-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_hotel_password_alter_contractattachement_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='HoteStars',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Instagram',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Linked_in',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='PlusCode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='accounting_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='accounting_phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='availabilityandrateprovider',
            field=models.CharField(blank=True, choices=[('ta', 'traveky admin'), ('aa', 'account admin')], default='ta', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='b2b',
            field=models.SmallIntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='b2c',
            field=models.SmallIntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='close_time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='reservation_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='reservation_phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='sales_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='sales_phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
