# Generated by Django 5.0.3 on 2024-07-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_roomicons_room_roomicons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='logo',
            new_name='main',
        ),
        migrations.AddField(
            model_name='room',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/images'),
        ),
        migrations.AddField(
            model_name='room',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/images'),
        ),
        migrations.AddField(
            model_name='room',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/images'),
        ),
    ]
