# Generated by Django 5.0.3 on 2024-07-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_hotel_options_alter_hotel_hotestars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
