# Generated by Django 5.0.3 on 2024-07-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_logo_room_main_room_first_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='main',
        ),
        migrations.RemoveField(
            model_name='room',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='third_image',
        ),
        migrations.AddField(
            model_name='roomphotos',
            name='type',
            field=models.SlugField(choices=[('D', 'descritpion image'), ('M', 'main image')], default=1),
            preserve_default=False,
        ),
    ]
