# Generated by Django 5.0.3 on 2024-07-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_room_first_image_remove_room_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomphotos',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/images'),
        ),
        migrations.AddField(
            model_name='room',
            name='main',
            field=models.ImageField(default=1, upload_to='rooms/logos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/images'),
        ),
        migrations.AddField(
            model_name='room',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/images'),
        ),
    ]
