# Generated by Django 5.0.3 on 2024-07-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_hotel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='descar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='descen',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='icons',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='long',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='policyar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='policyen',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
