# Generated by Django 5.0.3 on 2024-07-06 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='icon',
        ),
        migrations.AddField(
            model_name='icon',
            name='news_img',
            field=models.FileField(default=1, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'svg'])]),
            preserve_default=False,
        ),
    ]
