# Generated by Django 5.0.3 on 2024-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_icon_icon_icon_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombedoptions',
            name='count',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombedoptions',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icon',
            name='type',
            field=models.CharField(choices=[('h', 'hotel'), ('g', 'guets'), ('b', 'bed'), ('m', 'meal'), ('r', 'room')], max_length=255),
        ),
    ]
