# Generated by Django 5.0.3 on 2024-07-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_roombedoptions_count_roombedoptions_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedOptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.SmallIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='booking.roombedoptions')),
            ],
        ),
    ]
