# Generated by Django 5.0.3 on 2024-07-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_bedoptiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcountries',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
