# Generated by Django 5.0.3 on 2024-07-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_groupcountries_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombedoptions',
            name='price',
        ),
    ]
