# Generated by Django 5.0.3 on 2024-07-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_roombedoptions_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombedoptions',
            name='count',
        ),
        migrations.RemoveField(
            model_name='roombedoptions',
            name='type',
        ),
    ]
