# Generated by Django 5.0.3 on 2024-07-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_stopsale_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopsale',
            name='room',
        ),
    ]
