# Generated by Django 5.0.3 on 2024-07-09 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_remove_stopsale_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopsale',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.room'),
            preserve_default=False,
        ),
    ]
