# Generated by Django 5.0.3 on 2024-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_stopsale_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
