# Generated by Django 5.0.3 on 2024-07-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_groups_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='price',
            new_name='netrate',
        ),
    ]
