# Generated by Django 5.0.3 on 2024-07-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_rename_price_rate_netrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomguestoption',
            name='type',
        ),
        migrations.CreateModel(
            name='GuestOptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.SmallIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='booking.roomguestoption')),
            ],
        ),
    ]
