# Generated by Django 5.0.3 on 2024-07-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_roomguestoption_type_guestoptiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedoptiondetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_details', to='booking.roombedoptions'),
        ),
        migrations.AlterField(
            model_name='guestoptiondetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_details', to='booking.roomguestoption'),
        ),
    ]
