# Generated by Django 5.0.3 on 2024-07-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.SmallIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.periods')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.update')),
            ],
        ),
    ]
