# Generated by Django 5.0.3 on 2024-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_updatedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='percent',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='value',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='updatedetails',
            name='val',
            field=models.SmallIntegerField(null=True),
        ),
    ]
