# Generated by Django 5.0.3 on 2024-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_supplement_hotel_emails_extraservices_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityperoiodsdetails',
            name='val',
            field=models.IntegerField(null=True),
        ),
    ]
