# Generated by Django 5.0.3 on 2024-06-26 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.TextField()),
                ('city', models.TextField(blank=True, null=True)),
                ('phonenumber', models.TextField()),
                ('Googlereviewnumber', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('facebookaccount', models.TextField(blank=True, null=True)),
                ('verticalline', models.TextField(blank=True, null=True)),
                ('horizontalline', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namear', models.CharField(max_length=255)),
                ('nameen', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('HoteStars', models.SmallIntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('descar', models.TextField()),
                ('descen', models.TextField()),
                ('policyen', models.TextField()),
                ('policyar', models.TextField()),
                ('icons', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namear', models.CharField(max_length=255)),
                ('nameen', models.CharField(max_length=255)),
                ('descar', models.TextField()),
                ('descen', models.TextField()),
                ('guestgoup', models.TextField(blank=True, null=True)),
                ('Roomicons', models.TextField(blank=True, null=True)),
                ('roombeds', models.TextField(blank=True, null=True)),
                ('roomguests', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel/images')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='superadmin.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.hoteladmin')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='room/images')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='superadmin.room')),
            ],
        ),
    ]
