# Generated by Django 5.0.3 on 2024-06-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_remove_photos_hote_delete_hoteladmin_delete_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomphotos',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomPhotos',
        ),
    ]
